### ISSUE TITLE
pytime.father() wrong for non-US countries

### ISSUE THREAD

**Issue by Marmeladenbrot** [shnode/PyTime#8]
pytime.father(2020) gives me 2020-06-21
pytime.father(2021) gives me 2021-06-20

But for germany that day is on the 2020-05-21 / 2021-05-13.

Is there any way to get the fatherday for other countries?

**Comment by shinux** [comment]
I just noticed that Father's Day in Germany is 40 days after Easter and for some other countries those are totally different days. How about we add a `pytime.vatertag` API and get the right day.

**Comment by Marmeladenbrot** [comment]
Sure, sounds good 👍 

pytime.muttertag()
pytime.blackfriday()
pytime.cyberweek()

would also be nice (I use your package for unofficial holidays, getting semi-international marketing days would also be cool because I use those for my forecast models). But not sure if that is something you wanna add to your API.

**Comment by shinux** [comment]
Hi, @Marmeladenbrot I just added `pytime.vatertag` and bump this package to version 0.2.1, due to it's another kind of calculation.
For Muttertag you can still use `pytime.mother` because Mother's Day in Germany is also the 2nd Sunday in May.
And for black friday It's just the day after Thanksgiving Day, so just use `pytime.after(pytime.thanks(2020), "1day")`.

There are so many traditional festivals and new festivals created these years like you said around the whole planet, and I have not yet found a good solution for them. 😞

**Comment by shinux** [comment]
https://github.com/dr-prodigy/python-holidays
